[package]
name = "librespot"
version = "0.1.6"
authors = ["Librespot Org"]
license = "MIT"
description = "An open source client library for Spotify, with support for Spotify Connect"
keywords = ["spotify"]
repository = "https://github.com/librespot-org/librespot"
readme = "README.md"
edition = "2018"

[workspace]

[lib]
name = "librespot"
path = "src/lib.rs"

[[bin]]
name = "librespot"
path = "src/main.rs"
doc = false

[dependencies.librespot-audio]
path = "audio"
version = "0.1.6"
optional = true

[dependencies.librespot-connect]
path = "connect"
version = "0.1.6"
optional = true

[dependencies.librespot-core]
path = "core"
version = "0.1.6"
optional = true

[dependencies.librespot-metadata]
path = "metadata"
version = "0.1.6"
optional = true

[dependencies.librespot-playback]
path = "playback"
version = "0.1.6"
optional = true

[dependencies.librespot-protocol]
path = "protocol"
version = "0.1.6"
optional = true

[dependencies]
base64 = "0.13"
env_logger =  {version = "0.8", default-features = false, features = ["termcolor","humantime","atty"]}
futures = "0.1"
getopts = "0.2"
hyper = "0.11"
log = "0.4"
num-bigint = "0.3"
protobuf = "~2.14.0"
rand = "0.7"
rpassword = "5.0"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-process = "0.2"
tokio-signal = "0.2"
url = "1.7"
sha-1 = "0.8"
hex = "0.4"

[features]
alsa-backend = ["librespot-playback/alsa-backend", "playback"]
portaudio-backend = ["librespot-playback/portaudio-backend", "playback"]
pulseaudio-backend = ["librespot-playback/pulseaudio-backend", "playback"]
jackaudio-backend = ["librespot-playback/jackaudio-backend", "playback"]
rodio-backend = ["librespot-playback/rodio-backend", "playback"]
rodiojack-backend = ["librespot-playback/rodiojack-backend", "playback"]
sdl-backend = ["librespot-playback/sdl-backend", "playback"]
gstreamer-backend = ["librespot-playback/gstreamer-backend", "playback"]

with-tremor = ["librespot-audio/with-tremor", "audio"]
with-vorbis = ["librespot-audio/with-vorbis", "audio"]

with-dns-sd = ["librespot-connect/with-dns-sd", "connect"]

protocol = ["librespot-protocol"]
core = ["protocol", "librespot-core"]
audio = ["core", "librespot-audio"]
metadata = ["core", "librespot-metadata"]
playback = ["metadata", "audio", "core", "librespot-playback"]
connect = ["core", "playback", "protocol", "librespot-connect"]

default = ["rodio-backend", "connect"]

[package.metadata.deb]
maintainer = "librespot-org"
copyright = "2018 Paul Liétar"
license-file = ["LICENSE", "4"]
depends = "$auto"
extended-description = """\
librespot is an open source client library for Spotify. It enables applications \
to use Spotify's service, without using the official but closed-source \
libspotify. Additionally, it will provide extra features which are not \
available in the official library."""
section = "sound"
priority = "optional"
assets = [
    ["target/release/librespot", "usr/bin/", "755"],
    ["contrib/librespot.service", "lib/systemd/system/", "644"]
]
